# Generated by Django 5.1.4 on 2025-02-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_post_caption_alter_post_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
